### ISSUE TITLE
ledd crashing on 7050-QX-32S

### ISSUE THREAD

**Issue by taoyl-ms** [aristanetworks/sonic#25]
We are observing ledd keeps crashing on a 7050-qx-32s box in our environment. From syslog, it looks like it is trying to read from a sysfs path which does not exist. This device is running a SONiC March release image.

```
/var/log/syslog.1:Aug 30 23:58:44.933637 sonic-14 INFO ledd: Starting up...
/var/log/syslog.1:Aug 30 23:58:45.697043 sonic-14 INFO ledd: Loaded module 'led_control'.
/var/log/syslog.1:Aug 30 23:58:45.697739 sonic-14 INFO supervisord: ledd Traceback (most recent call last):
/var/log/syslog.1:Aug 30 23:58:45.697885 sonic-14 INFO supervisord: ledd   File "/usr/bin/ledd", line 225, in <module>
/var/log/syslog.1:Aug 30 23:58:45.698386 sonic-14 INFO pmon.sh[4220]: 2018-08-30 23:58:45,697 INFO success: ledd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
/var/log/syslog.1:Aug 30 23:58:45.699264 sonic-14 INFO supervisord: ledd     main()
/var/log/syslog.1:Aug 30 23:58:45.699264 sonic-14 INFO supervisord: ledd   File "/usr/bin/ledd", line 192, in main
/var/log/syslog.1:Aug 30 23:58:45.699264 sonic-14 INFO supervisord: ledd     err = load_platform_led_control_module()
/var/log/syslog.1:Aug 30 23:58:45.699264 sonic-14 INFO supervisord: ledd   File "/usr/bin/ledd", line 147, in load_platform_led_control_module
/var/log/syslog.1:Aug 30 23:58:45.699296 sonic-14 INFO supervisord: ledd     led_control = led_control_class()
/var/log/syslog.1:Aug 30 23:58:45.699315 sonic-14 INFO supervisord: ledd   File "/usr/share/sonic/platform/plugins/led_control.py", line 84, in __init__
/var/log/syslog.1:Aug 30 23:58:45.699315 sonic-14 INFO supervisord: ledd     with open("/sys/devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-0060/hwmon/hwmon4/fan1_led", "w") as f:
/var/log/syslog.1:Aug 30 23:58:45.699582 sonic-14 INFO supervisord: ledd IOError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-0060/hwmon/hwmon4/fan1_led'
/var/log/syslog.1:Aug 30 23:58:45.715067 sonic-14 INFO pmon.sh[4220]: 2018-08-30 23:58:45,714 INFO exited: ledd (exit status 1; not expected)
/var/log/syslog.1:Aug 30 23:58:46.718606 sonic-14 INFO pmon.sh[4220]: 2018-08-30 23:58:46,717 INFO spawned: 'ledd' with pid 16587
 
 
 
taoyl@sonic-14:/sys/devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-0060$ ls
leds  modalias  name  power  subsystem  uevent
taoyl@sonic-14:/sys/devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-0060/leds/fan1$ ls
brightness  device  max_brightness  power  subsystem  trigger  uevent


taoyl@sonic-14:~$ ls /sys/devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-0060/  
leds  modalias  name  power  subsystem  uevent

taoyl@sonic-14:~$ ls -l /sys/class/hwmon/ 
total 0
lrwxrwxrwx 1 root root 0 May  2 20:47 hwmon0 -> ../../devices/pci0000:00/0000:00:18.4/hwmon/hwmon0
lrwxrwxrwx 1 root root 0 May  2 20:44 hwmon1 -> ../../devices/pci0000:00/0000:00:18.3/hwmon/hwmon1
lrwxrwxrwx 1 root root 0 May  2 20:44 hwmon2 -> ../../devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-2/2-004c/hwmon/hwmon2
lrwxrwxrwx 1 root root 0 May  2 20:44 hwmon3 -> ../../devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-3/3-004c/hwmon/hwmon3
lrwxrwxrwx 1 root root 0 May  2 20:47 hwmon4 -> ../../devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-5/5-0058/hwmon/hwmon4
lrwxrwxrwx 1 root root 0 May  2 20:47 hwmon5 -> ../../devices/pci0000:00/0000:00:02.2/0000:02:00.0/i2c-6/6-0058/hwmon/hwmon5

```

fans are not showing in `sensors` and fancontrol is no longer running.

**Comment by Staphylo** [comment]
fixed by 3a215d159b4b9d4c95d3042555dcd5b0e8cc568d and 3e23c1c2a7627f85ab8d010a8edd0c6dad3ea235
