### ISSUE TITLE
[chassis] [linecards] [sup] syslog errors when testing container autorestart

### ISSUE THREAD

**Issue by wenyiz2021** [aristanetworks/sonic#80]
Following are syslog errors when running test_container_autorestart.py, causing 26 errors:

Wolverine card:
1.
```
2023-02-04T14:47:29.8828027Z E               Feb  4 12:02:36.428379 str2-7804-lc5-1 ERR lldp0#lldp-syncd [lldp_syncd] ERROR: Could not infer system information from: {'id': {'type': '', 'value': ''}, 'capability': [{'type': 'Other', 'enabled': True}, {'type': 'Wlan', 'enabled': True}]}#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/lldp_syncd/daemon.py", line 302, in parse_chassis#012    chassis_id_subtype = str(self.ChassisIdSubtypeMap[id_attributes['type']].value)#012  File "/usr/lib/python3.9/enum.py", line 408, in __getitem__#012    return cls._member_map_[name]#012KeyError: ''
```
2.
```
2023-02-04T14:47:29.8998828Z E               Feb  4 12:29:21.272496 str2-7804-lc5-1 ERR syncd0#syncd: :- threadFunction: time span WD exceeded 30082 ms for create:SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000
2023-02-04T14:47:29.8999745Z E               
2023-02-04T14:47:29.9000748Z E               Feb  4 12:29:21.272496 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: op: create, key: SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000
2023-02-04T14:47:29.9001551Z E               
2023-02-04T14:47:29.9002483Z E               Feb  4 12:29:21.272496 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_INIT_SWITCH: true
2023-02-04T14:47:29.9003188Z E               
2023-02-04T14:47:29.9004129Z E               Feb  4 12:29:21.272496 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x56069f7d3740
2023-02-04T14:47:29.9004897Z E               
2023-02-04T14:47:29.9005937Z E               Feb  4 12:29:21.272496 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x56069f7d3750
2023-02-04T14:47:29.9006830Z E               
2023-02-04T14:47:29.9007834Z E               Feb  4 12:29:21.272542 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_SWITCH_SHUTDOWN_REQUEST_NOTIFY: 0x56069f7d3770
2023-02-04T14:47:29.9009130Z E               
2023-02-04T14:47:29.9010216Z E               Feb  4 12:29:21.272542 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_SRC_MAC_ADDRESS: 2C:DD:E9:6C:CC:7D
2023-02-04T14:47:29.9010990Z E               
2023-02-04T14:47:29.9011983Z E               Feb  4 12:29:21.272569 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO: 7:48,54,58,48,48,46,48
2023-02-04T14:47:29.9012784Z E               
2023-02-04T14:47:29.9013739Z E               Feb  4 12:29:21.272569 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_TYPE: SAI_SWITCH_TYPE_VOQ
2023-02-04T14:47:29.9014423Z E               
2023-02-04T14:47:29.9015319Z E               Feb  4 12:29:21.272582 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_SWITCH_ID: 2
2023-02-04T14:47:29.9016013Z E               
2023-02-04T14:47:29.9016946Z E               Feb  4 12:29:21.272592 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_MAX_SYSTEM_CORES: 16
2023-02-04T14:47:29.9017616Z E               
2023-02-04T14:47:29.9048051Z E               Feb  4 12:29:21.272649 str2-7804-lc5-1 ERR syncd0#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_SYSTEM_PORT_CONFIG_LIST: {"count":144,"list":
...
```
3.
```
2023-02-04T14:47:29.9343862Z E               Feb  4 12:29:52.401667 str2-7804-lc5-1 ERR swss0#orchagent: :- doLagMemberTask: Failed to locate port str2-7804-lc3-1|ASIC0|Ethernet0
2023-02-04T14:47:29.9344651Z E               
2023-02-04T14:47:29.9345641Z E               Feb  4 12:29:52.401752 str2-7804-lc5-1 ERR swss0#orchagent: :- doLagMemberTask: Failed to locate port str2-7804-lc3-1|ASIC0|Ethernet4
...
```

4.
```
2023-02-04T14:47:30.0669357Z E               Feb  4 12:43:08.394026 str2-7804-lc5-1 ERR swss0#orchagent: :- handlePortStatusChangeNotification: Failed to get port object for port id 0x10000000000ec
2023-02-04T14:47:30.0670168Z E               
2023-02-04T14:47:30.0671217Z E               Feb  4 12:43:10.641664 str2-7804-lc5-1 ERR swss0#orchagent: :- handlePortStatusChangeNotification: Failed to get port object for port id 0x10000000000ec
```
Clearwater2 card:
5.
```
2023-02-04T14:47:30.1749228Z E               Feb  4 13:19:53.107082 str2-7804-lc6-1 ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is not running in namespace 'host' (3.0 minutes).
2023-02-04T14:47:30.1750010Z E               
2023-02-04T14:47:30.1751030Z E               Feb  4 13:20:53.166857 str2-7804-lc6-1 ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is not running in namespace 'host' (4.0 minutes).
2023-02-04T14:47:30.1751802Z E               
2023-02-04T14:47:30.1752810Z E               Feb  4 13:21:53.226848 str2-7804-lc6-1 ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is not running in namespace 'host' (5.0 minutes).
2023-02-04T14:47:30.1753590Z E               
2023-02-04T14:47:30.1754592Z E               Feb  4 13:22:09.955928 str2-7804-lc6-1 ERR syncd#supervisor-proc-exit-listener: Process 'syncd' is not running in namespace 'host' (1.0 minutes).
```

can you please help to identify each errors?
for point 3 it's an know issue that tries to get ports from card that is connected to chassis but not in use

**Comment by wenyiz2021** [comment]
@arlakshm @kenneth-arista @ysmanman

**Comment by wenyiz2021** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/7437 should help
