### ISSUE TITLE
[pmon] [CL2MS] [wolverine] chassisd keeps crashing on all linecards

### ISSUE THREAD

**Issue by wenyiz2021** [aristanetworks/sonic#97]
hi @Staphylo @kenneth-arista,
when running test_acl.py, there are pmon stacktrace issued and chassisd crashed, this is seen on both CL2MS and wolverine LC.
especially chassisd crashed and went back, then crashed again.

```
Sep 25 23:00:29.162227 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:29,160 INFO success: chassisd entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Sep 25 23:00:29.162268 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 597, in run
Sep 25 23:00:29.162310 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     self.module_updater.module_db_update()
Sep 25 23:00:29.162367 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 309, in module_db_update
Sep 25 23:00:29.162413 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     hostname_fvs = swsscommon.FieldValuePairs([(CHASSIS_MODULE_INFO_SLOT_FIELD, self.my_slot),
Sep 25 23:00:29.162450 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 229, in __init__
Sep 25 23:00:29.162488 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     _swsscommon.FieldValuePairs_swiginit(self, _swsscommon.new_FieldValuePairs(*args))
Sep 25 23:00:29.162525 str2-7804-lc5-1 INFO pmon#supervisord: chassisd TypeError: Wrong number or type of arguments for overloaded function 'new_FieldValuePairs'.
Sep 25 23:00:29.162562 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   Possible C/C++ prototypes are:
Sep 25 23:00:29.162604 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector()
Sep 25 23:00:29.163072 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > > const &)
Sep 25 23:00:29.163255 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > >::size_type)
Sep 25 23:00:29.163575 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > >::size_type,std::vector< std::pair< std::string,std::string > >::value_type const &)
Sep 25 23:00:29.216872 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:29,216 INFO exited: chassisd (exit status 1; not expected)
Sep 25 23:00:29.218329 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:29,217 INFO spawned: 'chassisd' with pid 139
Sep 25 23:00:39.229478 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:39,229 INFO success: chassisd entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Sep 25 23:00:39.532178 str2-7804-lc5-1 INFO pmon#supervisord: chassisd Traceback (most recent call last):
Sep 25 23:00:39.532226 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 624, in <module>
Sep 25 23:00:39.532263 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     main()
Sep 25 23:00:39.532284 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 619, in main
Sep 25 23:00:39.532303 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     chassisd.run()
Sep 25 23:00:39.532321 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 597, in run
Sep 25 23:00:39.532339 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     self.module_updater.module_db_update()
Sep 25 23:00:39.532356 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/local/bin/chassisd", line 309, in module_db_update
Sep 25 23:00:39.532376 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     hostname_fvs = swsscommon.FieldValuePairs([(CHASSIS_MODULE_INFO_SLOT_FIELD, self.my_slot),
Sep 25 23:00:39.532394 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 229, in __init__
Sep 25 23:00:39.532412 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     _swsscommon.FieldValuePairs_swiginit(self, _swsscommon.new_FieldValuePairs(*args))
Sep 25 23:00:39.532432 str2-7804-lc5-1 INFO pmon#supervisord: chassisd TypeError: Wrong number or type of arguments for overloaded function 'new_FieldValuePairs'.
Sep 25 23:00:39.532449 str2-7804-lc5-1 INFO pmon#supervisord: chassisd   Possible C/C++ prototypes are:
Sep 25 23:00:39.532468 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector()
Sep 25 23:00:39.532491 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > > const &)
Sep 25 23:00:39.532509 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > >::size_type)
Sep 25 23:00:39.532529 str2-7804-lc5-1 INFO pmon#supervisord: chassisd     std::vector< std::pair< std::string,std::string > >::vector(std::vector< std::pair< std::string,std::string > >::size_type,std::vector< std::pair< std::string,std::string > >::value_type const &)
Sep 25 23:00:39.564749 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:39,564 INFO exited: chassisd (exit status 1; not expected)
Sep 25 23:00:40.567011 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:40,566 INFO spawned: 'chassisd' with pid 140
Sep 25 23:00:50.577878 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-25 23:00:50,577 INFO success: chassisd entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
...
...

d::string > >::size_type,std::vector< std::pair< std::string,std::string > >::value_type const &)
Sep 26 04:09:59.189150 str2-7804-lc5-1 INFO pmon#supervisord 2023-09-26 04:09:59,188 INFO exited: chassisd (exit status 1; not expected)
Sep 26 04:09:59.603919 str2-7804-lc5-1 NOTICE swss0#orchagent: :- remove: Successfully deleted ACL rule DEFAULT_RULE in table DATA_INGRESS_IPV4_TEST
Sep 26 04:09:59.605330 str2-7804-lc5-1 NOTICE swss1#orchagent: :- remove: Successfully deleted ACL rule DEFAULT_RULE in table DATA_INGRESS_IPV4_TEST
```

till the end of ACL testing, before test deletes ACL rules, chassisd still crashed.

**Also noticed that chassisd keeps crashing all the time until now.**

admin@str2-7804-lc5-1:/var/log$ sudo docker exec -it pmon bash
root@str2-7804-lc5-1:/# ps aux | grep chassisd
root        1682 23.0  0.2  51124 38260 pts/0    S    20:58   0:00 /usr/bin/python3 /usr/local/bin/chassisd
root        1684  0.0  0.0   3240   644 pts/1    S+   20:58   0:00 grep chassisd
root@str2-7804-lc5-1:/# ps aux                
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1  30512 26116 pts/0    Ss+  18:36   0:06 /usr/bin/python3 /usr/local/bin/supervisord
root          18  0.0  0.1  29344 24048 pts/0    S    18:36   0:00 python3 /usr/bin/supervisor-proc-exit-listener --container-name pmon
root          19  0.0  0.0 220836  3732 pts/0    Sl   18:37   0:01 /usr/sbin/rsyslogd -n -iNONE
root          27  0.0  0.2  47576 34928 pts/0    S    18:37   0:00 python3 /usr/local/bin/ledd
root          29  0.2  0.2 274324 41440 pts/0    Sl   18:37   0:19 python3 /usr/local/bin/xcvrd
...
**root        1682  5.7  0.2  51124 38260 pts/0    S    20:58   0:00 /usr/bin/python3 /usr/local/bin/chassisd**
root        1685  0.0  0.0   6756  2796 pts/1    R+   20:58   0:00 ps aux

admin@str2-7804-lc5-1:/var/log$ date
**Tue 26 Sep 2023 09:00:41 PM UTC**
admin@str2-7804-lc5-1:/var/log$ sudo docker exec -it pmon bash
root@str2-7804-lc5-1:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1  30512 26116 pts/0    Ss+  18:36   0:06 /usr/bin/python3 /usr/local/bin/supervisord
root          18  0.0  0.1  29344 24048 pts/0    S    18:36   0:00 python3 /usr/bin/supervisor-proc-exit-listener --container-name pmon
root          19  0.0  0.0 220836  3732 pts/0    Sl   18:37   0:01 /usr/sbin/rsyslogd -n -iNONE
...
**root        1717 13.0  0.2  51124 38264 pts/0    S    21:00   0:00 /usr/bin/python3 /usr/local/bin/chassisd**
root        1724  0.0  0.0   6756  2888 pts/1    R+   21:00   0:00 ps aux

**Comment by wenyiz2021** [comment]
adding @arlakshm  for viz

**Comment by wenyiz2021** [comment]
https://github.com/sonic-net/sonic-platform-daemons/pull/396 has the fix
